### ISSUE TITLE
Will you accept PR for Flutter version?

### ISSUE THREAD

**Issue by fzyzcjy** [taoweiji/MixPush#13]
I may use it in a Flutter project, and I see "flutter version" being in you TODO list. Thus, I may create a PR if you want :)

**Comment by taoweiji** [comment]
You can try it, if there is no problem I will choose to merge.

**Comment by fzyzcjy** [comment]
OK I will try

**Comment by fzyzcjy** [comment]
你好，对PR/commit message等有要求吗，没有的话我就正常写了
