### ISSUE TITLE
Thread无释放操作

### ISSUE THREAD

**Issue by fzyzcjy** [taoweiji/MixPush#16]
你好，https://github.com/taoweiji/MixPush/blob/master/mixpush-core/src/main/java/com/mixpush/core/MixPushClient.java#L159 中的Thread似乎没有任何释放操作，似乎不太符合最佳实践……谢谢

p.s. 硬编码120s超时，似乎可以改成传参

**Comment by taoweiji** [comment]
看似不是很优雅，如果你有更好的建议可以提交给我，后续我也会持续进行调整。
