### ISSUE TITLE
onRegisterSucceed和getRegisterId的关系？

### ISSUE THREAD

**Issue by fzyzcjy** [taoweiji/MixPush#18]
你好，

请问onRegisterSucceed和getRegisterId的关系，如果在onRegisterSucceed中上传了regid，是否就可以无视getRegisterId（阅读README，我猜可能是？）

p.s. 用于正在开发的flutter库

谢谢

**Comment by taoweiji** [comment]
是的，两者只需要使用一种即可

**Comment by taoweiji** [comment]
这个是我们正在写的flutter插件，不过还没有完成，你也可以参考一下 https://github.com/taoweiji/flutter_mixpush

**Comment by fzyzcjy** [comment]
@taoweiji 额，我也正在写 https://github.com/fzyzcjy/flutter_push_notification

**Comment by fzyzcjy** [comment]
不过我的还包括标准的APNs（不是小米apns）

**Comment by taoweiji** [comment]
优秀！

**Comment by fzyzcjy** [comment]
发现个问题，小米读取成功后好像不会返回regid，因为onCommandResult的代码被注释掉了（参考：https://dev.mi.com/console/doc/detail?pId=41）
