### ISSUE TITLE
（建议）升级华为推送 4.0 -> 5.0，因为华为云发出了”4.0版本归档通知“

### ISSUE THREAD

**Issue by fzyzcjy** [taoweiji/MixPush#21]
”4.0版本归档通知“： https://developer.huawei.com/consumer/cn/doc/development/HMS-Guides/push-v4-removal-notice

**Comment by taoweiji** [comment]
收到，非常感谢你的反馈

**Comment by fzyzcjy** [comment]
不用谢，这个库很棒
