### ISSUE TITLE
后端MixPushMessage.platform似乎是无效参数，已被MixPushTarget.platforms替代？

### ISSUE THREAD

**Issue by fzyzcjy** [taoweiji/MixPush#23]
https://github.com/taoweiji/MixPush/blob/master/mixpush-sender/src/main/java/com/mixpush/sender/MixPushMessage.java#L17

全局查找似乎没找到使用的地方

p.s. 提个issue的原因：即使不修改，下一个使用者可能会更明确api用法（？）

**Comment by taoweiji** [comment]
这个是用于做日志使用的，没有其他地方使用

**Comment by taoweiji** [comment]
我这边考虑优化一下
