### ISSUE TITLE
设置默认推送平台无效

### ISSUE THREAD

**Issue by beiguancyc** [taoweiji/MixPush#24]
我在Application文件中设置
MixPushClient.getInstance().register(this,"huawei");

但是在Receiver里的onRegisterSucceed中，getPlatformName仍然是mi

**Comment by taoweiji** [comment]
因为huawei推送只支持华为手机，所以无法设置成默认的推送，sdk会根据依赖，默认选择最合适的推送

**Comment by beiguancyc** [comment]
感谢您的回复。

**Comment by taoweiji** [comment]
sdk内置的推送中，只有mi支持设置为默认推送平台；如果自定义一个第三方推送平台，比如信鸽之类的，这个值才真正生效。
