### ISSUE TITLE
华为推送的疑问

### ISSUE THREAD

**Issue by beiguancyc** [taoweiji/MixPush#25]
您好，目前正在测试集成您的这套框架的2.06，采用官网的网页版和我自己的js服务端向单个regid发送消息的办法，目前在测试华为平台时有如下问题：

集成后，onRegisterSucceed()可获得正确的id， 可以收到推送的消息，

但是onNotificationMessageArrived 和 onNotificationMessageClicked两个方法没有反应，IDE也没有相应的日志。

先前在集成小米推送的时候，如果Payload为空，onNotificationMessageArrived正常，onNotificationMessageClicked无反应

但是目前我的测试，使用华为推送，无论Payload是否为空，onNotificationMessageArrived 和 onNotificationMessageClicked两个方法均没有反应

希望得到您的帮助

**Comment by taoweiji** [comment]
只有小米、魅族推送才有onNotificationMessageArrived触发，而且是不保证一定调用的，因为APP被杀死后就不会回调了

**Comment by beiguancyc** [comment]
现在我测试的时候是在app打开的情况下，测试华为推送，收到华为推送后，点击通知栏，
onNotificationMessageClicked也不会触发。

**Comment by taoweiji** [comment]
你看看是不是 和这个问题是一样的 https://github.com/taoweiji/MixPush/issues/26

**Comment by beiguancyc** [comment]
不一样，同样的代码，使用小米就没问题，换成华为，能收到，但是点击通知栏没有反应，onNotificationMessageClicked也不会触发。

**Comment by taoweiji** [comment]
点击可以启动APP吗？我刚刚用华为手机进行测试，是可以正常收到的。

**Comment by taoweiji** [comment]
![image](https://user-images.githubusercontent.com/3044176/93081465-de7bd580-f6c1-11ea-8656-2abcbe2663ae.png)

会不会是发送消息的地方出错了？

**Comment by taoweiji** [comment]
我知道问题了，由于你是用后台进行推送的，所以推送的规则和MixPush不一样，导致无法正常打开，你要参考我的 [发送规则](https://github.com/taoweiji/MixPush/blob/master/mixpush-sender/src/main/java/com/mixpush/sender/provider/HuaweiPushProvider.java)

![image](https://user-images.githubusercontent.com/3044176/93082191-0d467b80-f6c3-11ea-8e23-80275c3a0a84.png)

**Comment by taoweiji** [comment]
你试试在后台 推送，选择 自定义点击行为，填写 mixpush://com.mixpush.huawei/message?payload=%7b%22url%22%3a%22http%3a%2f%2fsoso.com%22%7d

payload= 后面的内容就是推送的内容

**Comment by taoweiji** [comment]
![image](https://user-images.githubusercontent.com/3044176/93084208-4a603d00-f6c6-11ea-80b0-c4baff994c57.png)

**Comment by ForBetterSalary** [comment]
杀死进程情况下，收到通知点击通知是不会有回调的

**Comment by beiguancyc** [comment]
多谢指点，明天我安排测试一下，同时也会观察ov的推送测试。

**Comment by taoweiji** [comment]
OPPO填写 mixpush://com.mixpush.oppo/message?payload=%7b%22url%22%3a%22http%3a%2f%2fsoso.com%22%7d

**Comment by beiguancyc** [comment]
mixpush://com.mixpush.huawei/message?payload=%7b%22url%22%3a%22http%3a%2f%2fsoso.com%22%7d  
我按照截图一样的内容在华为后台发送push推送，可以接收到，但是点击后onNotificationMessageClicked依然没有相应。
刚才翻了翻华为的文档，发现华为的推送和别家不太一样，明天再试试

**Comment by beiguancyc** [comment]
多翻了翻华为的文档，以及把sender源码和华为的源码看了看，相对于小米来说，华为需要发送intentUri做成了必须参数，这点是我忽略的。
另外，在华为后台随手测试了下透传，用了华为的文档示例，
{
    "hps": {
            "msg" : {
                "type" : 1,
               "body" : {"key":"value"}
               }
    }
}
提示MixPushMessage为null

针对进程杀死无法拉起的情况，我也进行了测试，时间有限，其中小米推送拉活小米手机，华为推送拉活华为手机是没问题的，我用小米手机集成华为推送后，除了无法拉活，其他都正常。
