### ISSUE TITLE
华为推送

### ISSUE THREAD

**Issue by ForBetterSalary** [taoweiji/MixPush#26]
1：直接使用华为的推送，在杀死应用的情况下，可以拉起指定页面；集成MixPush,在杀死应用的情况下，在自定义的Receiver收不到华为点开通知的回调

**Comment by taoweiji** [comment]
那在前台收到推送后点击可以收到回调吗？

**Comment by ForBetterSalary** [comment]
只要应用不被杀死都没事。应用杀死情况下，无论是小米还是华为，都收不到回调，因为MixPushClient.getInstance().getHandler().getPushReceiver(),获取不到Receiver对象,会报错

**Comment by taoweiji** [comment]
如果是这个问题就好解决，你检查一下是不是你的setPushListener是不是在MyApplication的onCreate进行初始化，不能异步初始化哦
UnifiedPush.getInstance().setPushListener(new MyPushReceiver());
UnifiedPush.getInstance().register(this);

**Comment by beiguancyc** [comment]
我的情况是华为无论在何种情况，点击都收不到回调

**Comment by ForBetterSalary** [comment]
不行的，在杀死进程情况下回调是收不到的

**Comment by ForBetterSalary** [comment]
你说的setPushListener 没有这个方法，是setPushReceiver

**Comment by taoweiji** [comment]
那你在初始化的时候打印日志，然后点击通知栏，看看点击通知栏报错前是否已经进行初始化
