### ISSUE TITLE
 I can't import the UnifiedPush Class

### ISSUE THREAD

**Issue by liuxgchi** [taoweiji/MixPush#27]
* I added this MixPush sdk by the guide.I countered the error in the code screenshot.I wonder why I can't import the UnifiedPush Class.
![image](https://user-images.githubusercontent.com/7333031/93438632-2851ff00-f900-11ea-91d5-13c7197d85cf.png)
* further more, I can't distinguish the MixPush And UniedPush, the are seperated sdk belong to different developers?
thanks a lot and wating your help!

**Comment by liuxgchi** [comment]
你好，我按照集成文档那集成后，当在Application初始化时用到了UnifiedPush这个类，然后发现这个类没有导入，我前面完全是按照集成文档添加的依赖，请问是集成文档中的依赖没有写全吗？另外我有点疑惑，我看晚上有介绍一个统一推送的项目，这个同时以推送的项目其中有类叫UnifiedPush,请问MixPush和统一推送哪个项目是同一个项目吗？需要您的指导和帮助，感谢！

**Comment by taoweiji** [comment]
非常抱歉，应该是 MixPush，文档有误，已经改正，非常感谢你的反馈

**Comment by liuxgchi** [comment]
明白了，感谢回复
