### ISSUE TITLE
貌似不支付对单一设备推送吧。

### ISSUE THREAD

**Issue by wujingke** [taoweiji/MixPush#3]
建议提供一个设备ID   server能通过这个ID去那个通道推送

**Comment by taoweiji** [comment]
目前单一设备的推送建议使用别名去实现，一个用户绑定一台设备，比如登录的用户id是“1001”，那么设备绑定的别名也是“1001”，推送这个别名，这台设备就能收到了。
如果是说纯粹的设备唯一码，就需要服务端来实现了，客户端获取设备唯一码上传到服务端，服务端再根据唯一码来推送。

**Comment by wujingke** [comment]
别名还是需要同时调用3个接口

**Comment by wujingke** [comment]
比如 客户端调用个推getClientid返回的ID 前面加个getui_ 这类的 server端就能去判断走那个接口
