### ISSUE TITLE
魅族手机 MzSystemUtils.isMeizuAndFlyme()获取用于是false

### ISSUE THREAD

**Issue by lizhexun** [taoweiji/MixPush#34]
解决办法 MzSystemUtils.isMeizuAndFlyme() 换成MzSystemUtils.isMeizu(content)

**Comment by taoweiji** [comment]
你是什么型号的手机，可以提供一下系统信息的截图吗？我这边测试一下，回归代码。

**Comment by lizhexun** [comment]
魅族17 系统版本flyme8.2.0.0A，初始化总是默认成小米，debug调试后发现MeizuPushProvider->isSupport(Context context)->MzSystemUtils.isMeizuAndFlyme()返回始终为false, 测试发现使用MzSystemUtils.isMeizu(Context context) 方法后返回true.

**Comment by taoweiji** [comment]
好的，今晚更新包

**Comment by taoweiji** [comment]
已经打包了2.0.9版本
