### ISSUE TITLE
关于魅族手机不能正常获取regId,导致不能推送

### ISSUE THREAD

**Issue by lizhexun** [taoweiji/MixPush#35]
魅族17，Flyme8.2.0.0A 系统不能正常获取regI，查询官方文档，官方推荐使用 MzSystemUtils.isBrandMeizu(this) 来判断是否是魅族品牌，希望大佬更新发包啊，这样就又可以愉快的玩耍了

**Comment by taoweiji** [comment]
好的，晚上更新包

**Comment by taoweiji** [comment]
已经更新
