### ISSUE TITLE
onNotificationMessageArrived()和onNotificationMessageClicked()不执行？

### ISSUE THREAD

**Issue by liuxgchi** [taoweiji/MixPush#43]
onNotificationMessageArrived()和onNotificationMessageClicked()总是不执行？ 可能是什么原因呢？我查了半天也找不到可能性的原因？请给与支持一下，谢谢了！

MixPushClient.getInstance().setPushReceiver(new MyMixPushReceiver());
MixPushClient.getInstance().register(this);

public class MyMixPushReceiver extends MixPushReceiver {
  public static final String TAG = "mix";
  @Override
  public void onRegisterSucceed(Context context, MixPushPlatform mixPushPlatform) {
    // 这里需要实现上传regId和推送平台信息到服务端保存，
    //也可以通过MixPushClient.getInstance().getRegisterId的方式实现
    register2Backend(mixPushPlatform.getPlatformName().toUpperCase(),mixPushPlatform.getRegId());

  }

  @Override
  public void onNotificationMessageClicked(Context context, MixPushMessage message) {
    // TODO 通知栏消息点击触发，实现打开具体页面，打开浏览器等。
    Log.d(TAG, "onNotificationMessageClicked: " + message);
    WebViewActivity.startWebViewShowTitleBarWithFlags(context,"https://www.baidu.com");

  }

  /**
   * 通知栏消息消息到达回调
   */
  public void onNotificationMessageArrived(Context context, MixPushMessage message) {
    Log.d(TAG, "onNotificationMessageArrived: " + message);
    WebViewActivity.startWebViewShowTitleBarWithFlags(context,"https://www.baidu.com");

  }

**Comment by liuxgchi** [comment]
补充：华为渠道发送消息后，系统通知栏可以接收到消息，但是onNotificationMessageArrived()和onNotificationMessageClicked()总是不执行？

**Comment by liuxgchi** [comment]
这是个过程中的日志： 2021-05-12 10:52:37.237 24543-24951/com. D/mixpush: log: onRegisterSucceed PushPlatform{platformName='huawei', regId='IQAAAACy0Z-XAAAdEAi_LbY96xD-3eVAP6H8iOyIRT3i72M_hffqziabyVc94fJJaGfJ0jaCiqlNLdk1PhVblykoSYZ3ToDqB7j9W6xA0vULPzZrvQ'}
2021-05-12 10:52:37.238 24543-25095/com. D/mix: register2Backend: token 027ad1a43c9547c0b813bc1dc927a342
2021-05-12 11:09:48.947 24543-24543/com. D/mixpush: log: register notification huawei
2021-05-12 11:09:49.393 24543-26113/com. D/mixpush: log: 已经响应onRegisterSucceed,不再重复调用

**Comment by hero0812** [comment]
华为推送SDK 暂不支持回调，可以去华为推送官方文档看一下

**Comment by taoweiji** [comment]
测试正常，可以重新尝试
