### ISSUE TITLE
需要适配Android 12 ，否则无法安装

### ISSUE THREAD

**Issue by beiguancyc** [taoweiji/MixPush#55]
com.mixpush.huawei.HmsMessageReceiveActivity: Targeting S+ (version 31 and above) requires that an explicit value for android:exported be defined when intent filters are present'

需要添加android:exported="true"

**Comment by taoweiji** [comment]
什么型号的手机和版本无法安装？

**Comment by beiguancyc** [comment]
因为android 12的兼容性变化，https://developer.android.com/about/versions/12/behavior-changes-12
2.3.7版本打包的时候会报错 Targeting S+ (version 31 and above) requires that an explicit value for android:exported be defined when intent filters are present'
2.3.8就没这个问题了。
还有老兄，你把版本号写成2.4.8了。
<img width="285" alt="image" src="https://user-images.githubusercontent.com/12932389/176834154-40957c7d-8f86-4569-823f-dafc956e95a8.png">

**Comment by beiguancyc** [comment]
用2.3.8打的包，android 12还是没法安装

**Comment by beiguancyc** [comment]
测试可用
