### ISSUE TITLE
您的应用在用户同意隐私政策前申请获取用户的设备ID、IMEI、ANDROID ID个人信息，不符合华为应用市场审核标准

### ISSUE THREAD

**Issue by Amition** [taoweiji/MixPush#60]
"stackTrace":["android.app.ApplicationPackageManager.getInstalledPackages(ApplicationPackageManager.java:886)","com.huawei.hms.aaid.b.a.a(AaidUtils.java:91)","com.huawei.hms.aaid.b.a.b(AaidUtils.java:141)","com.huawei.hms.aaid.HmsInstanceId.getId(HmsInstanceId.java:100)","com.huawei.hms.aaid.HmsInstanceId.getToken(HmsInstanceId.java:191)","com.mixpush.huawei.HuaweiPushProvider.getRegisterId(HuaweiPushProvider.java:76)","com.mixpush.huawei.HuaweiPushProvider$1.run(HuaweiPushProvider.java:91)"]

**Comment by taoweiji** [comment]
建议在同意隐私政策后才注册推送
