### ISSUE TITLE
能否适配下android12

### ISSUE THREAD

**Issue by chengxuyuan12345** [taoweiji/MixPush#61]
android:exported needs to be explicitly specified for <activity>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined

**Comment by chengxuyuan12345** [comment]
只要有intent filter标签的都得加上android:exported

**Comment by taoweiji** [comment]
好的，我优化一下，能够提供一下测试机型吗

**Comment by chengxuyuan12345** [comment]
> 好的，我优化一下，能够提供一下测试机型吗

你把targetSdkVersion升级到31就会复线这个问题

**Comment by taoweiji** [comment]
好的，感谢提醒

**Comment by chengxuyuan12345** [comment]
这个register能改成根据传的platform去做初始化吗，不想一次性初始化那么多。

**Comment by taoweiji** [comment]
已经适配
