### ISSUE TITLE
希望作者支持一下华为推送

### ISSUE THREAD

**Issue by 836198048** [taoweiji/MixPush#8]
毕竟现在华为手机的使用率也很高==然而华为自家的推送其实也是个垃圾==

**Comment by watonyweng** [comment]
Huawei Message Service is similar to the Google Message Service. Therefore, for non-Huawei mobile phones, the push rate cannot be guaranteed.

**Comment by taoweiji** [comment]
2年后迎来了更新，欢迎继续关注
